name: CD Pipeline for Angular Frontend

on:
  push:
    branches:
      - staging
      - production

jobs:

  deploy:
    name: 🚀 Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519_frontend
          chmod 600 ~/.ssh/id_ed25519_frontend

      - name: SSH to VPS and deploy
        run: |
          TAG=staging
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519_frontend ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << EOF
            cd /home/${{ secrets.VPS_USER }}/frontend/$TAG
            docker compose pull
            docker compose down && docker compose up -d
          EOF
